version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123@db/prof_zadaniye

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=prof_zadaniye
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123